<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.POMwithPF.homepage.TC002_VerifyRegistration" tests="4" time="5.878" ignored="0" failures="1" timestamp="14 Mar 2018 08:31:00 GMT" skipped="3" hostname="Hrishikesh" errors="0">
  <testcase name="verifyRegistration" time="0.683" classname="com.POMwithPF.homepage.TC002_VerifyRegistration">
    <skipped/>
  </testcase> <!-- verifyRegistration -->
  <testcase name="verifyRegistration" time="0.583" classname="com.POMwithPF.homepage.TC002_VerifyRegistration">
    <failure type="java.lang.AssertionError" message="verifyRegistration expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: verifyRegistration expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.POMwithPF.homepage.TC002_VerifyRegistration.verifyRegistration(TC002_VerifyRegistration.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyRegistration -->
  <testcase name="verifyRegistration" time="0.716" classname="com.POMwithPF.homepage.TC002_VerifyRegistration">
    <skipped/>
  </testcase> <!-- verifyRegistration -->
  <testcase name="verifyRegistration" time="3.896" classname="com.POMwithPF.homepage.TC002_VerifyRegistration">
    <skipped/>
  </testcase> <!-- verifyRegistration -->
</testsuite> <!-- com.POMwithPF.homepage.TC002_VerifyRegistration -->
